### ISSUE TITLE
[bug] Unable to activate v14 on 10.8 (master branch)

### ISSUE THREAD

**Issue by sproberts92** [jellyfin/jellyfin-plugin-ldapauth#104]
Fedora 35 on Raspberry Pi 4 (aarch64), built from commit [29f92724e](https://github.com/jellyfin/jellyfin/commit/29f92724ef1919402db32483632de03e4cbf2585) of Jellyfin. Same behaviour in 3-4 other 10.8.0 era commits I've tried over the last month or so.

All of the following were reliably produced by:
1. Removing any existing versions of the LDAP plugin
2. Removing any existing LDAP config in `/var/lib/jellyfin/plugins/configurations`
3. Restarting Jellyfin via systemctl
4. Installing the given version from the catalog
5. Restarting Jellyfin via systemctl

Version 14.0.0.0 is unable to activate, version 12.0.0.0 is fine:

* Version 14.0.0.0 throws the error shown in the following log:
![image](https://user-images.githubusercontent.com/5414367/151351193-194bbab6-4dfe-4f91-bb9d-01d01e640438.png)
```
[20:09:59] [INF] [1] Main: Jellyfin version: 10.8.0
[20:10:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/libexec/jellyfin/restart.sh]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin-web]"]
[20:10:00] [INF] [1] Main: Arguments: ["/usr/lib64/jellyfin/jellyfin.dll", "--webdir=/usr/share/jellyfin-web", "--restartpath=/usr/libexec/jellyfin/restart.sh"]
[20:10:00] [INF] [1] Main: Operating system: Linux
[20:10:00] [INF] [1] Main: Architecture: Arm64
[20:10:00] [INF] [1] Main: 64-Bit Process: True
[20:10:00] [INF] [1] Main: User Interactive: True
[20:10:00] [INF] [1] Main: Processor count: 4
[20:10:00] [INF] [1] Main: Program data path: /var/lib/jellyfin
[20:10:00] [INF] [1] Main: Web resources path: /usr/share/jellyfin-web
[20:10:00] [INF] [1] Main: Application directory: /usr/lib64/jellyfin/
[20:10:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /var/cache/jellyfin
[20:10:01] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[20:10:01] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /var/lib/jellyfin/plugins/LDAP Authentication_14.0.0.0/LDAP-Auth.dll. Unknown exception was thrown. Disabling plugin.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[20:10:01] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Novell.Directory.Ldap.NETStandard, Version=3.6.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx from /var/lib/jellyfin/plugins/LDAP Authentication_14.0.0.0/Novell.Directory.Ldap.NETStandard.dll
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of MediaBrowser.Common.Providers.SubtitleConfigurationFactory
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of MediaBrowser.Controller.Library.MetadataConfigurationStore
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Emby.Server.Implementations.LiveTv.LiveTvConfigurationFactory
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Emby.Server.Implementations.Branding.BrandingConfigurationFactory
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of MediaBrowser.MediaEncoding.Configuration.EncodingConfigurationFactory
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Emby.Dlna.DlnaConfigurationFactory
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Emby.Notifications.NotificationConfigurationFactory
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of MediaBrowser.XbmcMetadata.Configuration.NfoConfigurationFactory
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Jellyfin.Networking.Configuration.NetworkConfigurationFactory
[20:10:01] [DBG] [1] Emby.Server.Implementations.ApplicationHost: Creating instance of Jellyfin.Server.Migrations.MigrationsFactory
```
* Version 13.0.0.0 seems to get confused about whether it's installing 13.0.0.0 or 14.0.0.0, but the logs do also show a failure to activate 13.0.0.0:
![image](https://user-images.githubusercontent.com/5414367/151350076-3cb42194-b6f3-4b31-bad4-2533fbb85e01.png)
```
[22:25:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /var/lib/jellyfin/plugins/LDAP Authentication_13.0.0.0/LDAP-Auth.dll. Unknown exception was thrown. Disabling plugin.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
[22:25:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Novell.Directory.Ldap.NETStandard, Version=3.6.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx from /var/lib/jellyfin/plugins/LDAP Authentication_13.0.0.0/Novell.Directory.Ldap.NETStandard.dll
```
* Version 12.0.0.0 is able to install and activate ok:
![2022-01-27T22:20:40+1100](https://user-images.githubusercontent.com/5414367/151349604-08d717fa-c5ba-494b-a672-5b8f078ac00e.png)
```
[22:17:51] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly LDAP-Auth, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/LDAP Authentication_12.0.0.0/LDAP-Auth.dll
[22:17:51] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Novell.Directory.Ldap.NETStandard, Version=3.6.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx from /var/lib/jellyfin/plugins/LDAP Authentication_12.0.0.0/Novell.Directory.Ldap.NETStandard.dll
```

I'm not a C# guy, so my knowledge of where to troubleshoot is limited, but from some searching it seems to be an issue with finding a particular .NET dependency. So that leads me to believe that something needs to be added/adjusted in the package manifest.

I have attempted to install `dotnet-runtime-6.0`, but there was no change in behaviour. I have also tried building the plugin myself, both on the Raspberry Pi and another x86 machine.

Note: I don't know the significance of the `PublicKeyToken` values, so I have removed them. They show real values in the log.

**Comment by sproberts92** [comment]
Embarrassingly for me, but happily for you, it turns out that my latest built binaries had not installed properly. Forcing the install with rpm has solved the issue.
