### ISSUE TITLE
Connection to LDAP server fail with STARTTLS

### ISSUE THREAD

**Issue by Psyoknight** [jellyfin/jellyfin-plugin-ldapauth#12]
Hi,

I'm having problem to get the plugin working in my configuration. I think it's related to STARTTLS but could be wrong.

On my server, I have OpenLDAP installed and configured with STARTTLS listening on port 389. Jellyfin is installed on the same machine, so I configured the LDAP Server as "localhost" (tried 127.0.0.1, real IP and FQDN too) on port 389.

Without "Secure LDAP" (which seems to refer to SSL, not STARTTLS) enabled in the plugin configuration, logs says it should be enabled. With "Secure LDAP" enabled, I have this in my logs : 

```
[2019-07-24 23:44:42.118 +02:00] [ERR] Failed to Connect or Bind to server
LdapException: Unable to connect to server localhost:389 (91) Connect Error
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at Novell.Directory.Ldap.AsyncExtensions.WaitAndUnwrap(Task task, Int32 timeout)
   at Novell.Directory.Ldap.Connection.connect(String host, Int32 port, Int32 semaphoreId)
[2019-07-24 23:44:42.153 +02:00] [ERR] Error authenticating with provider "LDAP-Authentication"
LdapException: Unable to connect to server localhost:389 (91) Connect Error
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at Novell.Directory.Ldap.AsyncExtensions.WaitAndUnwrap(Task task, Int32 timeout)
   at Novell.Directory.Ldap.Connection.connect(String host, Int32 port, Int32 semaphoreId)
[2019-07-24 23:44:42.161 +02:00] [ERR] Error authenticating with provider "Default"
System.Exception: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2019-07-24 23:44:42.167 +02:00] [ERR] Error authenticating with provider "InvalidOrMissingAuthenticationProvider"
MediaBrowser.Controller.Net.SecurityException: User Account cannot login with this provider. The Normal provider for this user cannot be found
   at Emby.Server.Implementations.Library.InvalidAuthProvider.Authenticate(String username, String password)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2019-07-24 23:44:42.192 +02:00] [ERR] Invalid username or password entered.
```
   
I also have a bunch of other apps on this server which are working well with STARTTLS (Nextcloud, Gitea, ...), so I'm pretty confident about my OpenLDAP configuration.

Am I doing this wrong ? Is STARTTLS not supported ? 

Thanks a lot for your work !

**Comment by joshuaboniface** [comment]
So it seems like this is technically supported (https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/master/src/Novell.Directory.Ldap.NETStandard/Connection.cs) but we didn't implement this, so for the plugin STARTTLS is not currently supported. I'd mess around with it myself, but I don't use any TLS on my LDAP setup so I have no real way to test.

**Comment by Psyoknight** [comment]
Ok, thank you for your answer. At least, it comforts me, that's not a configuration error on my side.

I'm willing to test any of your code if necessary. I'm not a dev, but I'm a sysadmin so I'm not afraid to setup a testing infrastructure for this.

**Comment by nxtfsm** [comment]
> https://github.com/LogicalPhallacy/jellyfin-plugin-ldapauth Can you give my dev branch of the plugin a try? It has a setting to enable TLS and it will try to start and stop if it is enabled

Hi - This is a new account and I'm mostly new to git in general, but I've run into exactly this problem and would really like to give your branch a try... but can you post or link to the steps to swap the plugin installed through the Jellyfin browser ui to a clone of a dev branch? Thanks!

**Comment by Psyoknight** [comment]
Hi @LogicalPhallacy ,

Thanks a lot for your work on this. I will give it a try soon. Got busy at work these days, but I will have some time at the end of the week to setup a testing infrastructure. 

@nxtfsm I did not start to look at all of this yet, but you may check this repo : https://github.com/jellyfin/jellyfin-build . Additionnaly, I generaly wouldn't recommand to swap on your production environnement, but on a testing one if you can. (but could be ok, though =D )

**Comment by ccellist** [comment]
Hello; did this ever get fixed? I have v. 6.0.0 of this plugin but I'm getting the same error:
```
   at Novell.Directory.Ldap.Connection.connect(String host, Int32 port, Int32 semaphoreId)
[04:39:56] [ERR] Error processing request
LdapException: Unable to connect to server ldap.server.arayahome.net:389 (91) Connect Error
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncStat
e)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallb
ack asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__44_0(String arg1, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost)
   at Novell.Directory.Ldap.Connection.connect(String host, Int32 port, Int32 semaphoreId)
```

If I disable LDAP over SSL I get an instance exception. Sadly ldap seems irreparably broken on my Jellyfin system right now, no matter which version of the plugin I use. Thanks.
