### ISSUE TITLE
OpenLDAP Issue

### ISSUE THREAD

**Issue by eudojosegonzalez** [jellyfin/jellyfin-plugin-ldapauth#126]
Hi 
Cheers
I have the following problem when using the Jellyfin Ldap plugin

from the web administrator, when making the queries, it connects to the LDAP server, makes the queries and gets users

However, when I try to enter with a user created in OpenLDAP, Jellyfin shows me a user not found.

This is the server log

Error authenticating with provider "LDAP-Authentication"
MediaBrowser.Controller.Authentication.AuthenticationException: Error completing LDAP login. Invalid username or password.
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.ConnectToLdap(String userDn, String userPassword)
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)

**Comment by crobibero** [comment]
This isnt really enough information to provide any assistance to, but I can confirm that the Jellyfin plugin can connect to OpenLDAP.

**Comment by eudojosegonzalez** [comment]
Thanks for your quick response

What other information do you need so that you can better guide me?

LDAP Structure
dc=ninatv
ou=Clientes

Jellyfin Plugin configuration

LDAP Bind User
CN=administrator,DC=ninatv

LDAP User Filter
(objectClass=inetOrgPerson)

LDAP Attributes:
uid, cn, mail, displayName

**Comment by AnthonyRcd** [comment]
Have you created the "Enable User Creation" option in the plugin configuration ? This is what enables Jellyfin to create a user in its database from the LDAP server you created your user in.

![Screenshot 2022-10-13 at 22-55-02 Jellyfin](https://user-images.githubusercontent.com/22835950/195708777-77d466a4-5d6c-433e-b70d-948f9756062a.png)
