### ISSUE TITLE
LDAP Admin Filter issue, preventing any login

### ISSUE THREAD

**Issue by chjud** [jellyfin/jellyfin-plugin-ldapauth#128]
Using the LDAP Plugin v16 with Jellyfin on Docker. Everything works up to the point of testing the plugin against the username and the number of users.

- LDAP Testing within the plugin is successful. User and Admin Count are correct from LDAP Server, Username can be successfully validated
- If there is no "LDAP Admin Base DN" and no "LDAP Admin Filter" configured, the LDAP, the LDAP user login is sucessful
- If these two options above are configured, the user login is not possible, wether by an admin user nor a normal user. The error log reads then as below:
**************Log
[2022-09-07 19:36:30.150 +00:00] [ERR] [83] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: Failed to Connect or Bind to server as user "uid=XXXX,cn=users,dc=xxxxxxx,dc=ccc"
LdapException: Invalid Credentials (49) Invalid Credentials
LdapException: Matched DN: 
[2022-09-07 19:36:30.152 +00:00] [ERR] [83] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "LDAP-Authentication"
MediaBrowser.Controller.Authentication.AuthenticationException: Error completing LDAP login. Invalid username or password.
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.ConnectToLdap(String userDn, String userPassword)
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2022-09-07 19:36:30.200 +00:00] [INF] [83] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "XXXXX" has been denied (IP: "19x.xx.xx.x").
[2022-09-07 19:36:30.202 +00:00] [ERR] [83] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Invalid username or password entered". URL "POST" "/Users/authenticatebyname".
*****************

I tried an endless variety of options, but no avail. One of them icluded the suggestion to extend the user base with the admin and user groups: (|(memberOf=CN=JellyfinUsers,cn=groups,DC=xxxxxxx,DC=ccc)(memberOf=CN=JellyfinAdmins,CN=groups,DC=xxxxxxx,DC=ccc))
Also not solving the problem

**Comment by chjud** [comment]
After I thought I tried everything and posted here, I just needed another try... the solution is far simpler than I thought. I am almost ashamed to write it here... but hope it helps someone else:
The ""LDAP Admin Base DN" is most likely similar to the "LDAP Base DN" configured earlier and not anything more specific. At least that was my mistake. As "LDAP Admin Filter" I used the group associated/created for Admins.
