### ISSUE TITLE
FreeIPA LDAP Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by danukefl** [jellyfin/jellyfin-plugin-ldapauth#16]
I'm not sure if this is an issue with my configuration or if it is related to FreeIPA but I am receiving the below error when attempting to authenticate over LDAP with a FreeIPA server. I am planning on setting up a different test one for compatibility testing soon. The user/admin filters, and bind user test correctly using ldapsearch.

The instance is running in docker using the linuxserver image and the error occurs when directly connecting or through a reverse proxy, and across multiple browsers (chrome desktop and android, firefox)

`[22:18:49] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateLocalUser(String username, String password, String hashedPassword, User user, String remoteEndPoint)
   at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

Config Info, server and bind user not listed but validated. 
LDAP Base DN for searches: cn=accounts,dc=example,dc=com
LDAP Attributes: uid
LDAP Name Attribute: cn
LDAP User Filter: (&(objectClass=person)(memberof=cn=airsonic_users,cn=groups,cn=accounts,dc=example,dc=com))
LDAP Admin Filter: (&(objectClass=person)(memberof=cn=airsonic_admins,cn=groups,cn=accounts,dc=example,dc=com))

As always, any help is appreciated!

**Comment by danukefl** [comment]
Disregard, too many late nights. I was thinking LDAP Attributes as user login, and LDAP Name Attribute as display name. Changing both to UID corrects the issue.
