### ISSUE TITLE
Can't uninstall 6.0 on 10.4.3

### ISSUE THREAD

**Issue by charredchar** [jellyfin/jellyfin-plugin-ldapauth#41]
I've been having non-stop issues with getting the LDAP plugin to work with my Active Directory Domain... I have it working just fine for NextCloud so I know everything on my end is working as it should.
During attempts to troubleshoot this I am attempting Jellyfin Server 10.4.3 because I was told (on reddit) that it has less issues than 10.5. Well, still not working.
I am now trying to remove 6.0 of the pluigin to install 4.0 for testing to see if it reacts any different. It won't uninstall. The plugins page just hangs on a progress wheel and I see the following in the log.

`[2020-07-11 20:15:17.630 -05:00] [ERR] Error processing request
System.UnauthorizedAccessException: Access to the path 'LDAP-Auth.dll' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Emby.Server.Implementations.Updates.InstallationManager.UninstallPlugin(IPlugin plugin)
   at MediaBrowser.Api.PluginService.Delete(UninstallPlugin request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by oddstr13** [comment]
This is an issue with Windows and file locking.
The server cannot delete the plugin file while the plugin is loaded on Windows.

Unfortunately, in order to uninstall, you need to stop the server, then delete the plugin files from disk.
