### ISSUE TITLE
Update from v6 to v9

### ISSUE THREAD

**Issue by arantes555** [jellyfin/jellyfin-plugin-ldapauth#54]
Hello all !

I have a problem trying to update my Jellyfin install to 10.5 with the v6 LdapAuth plugin, to 10.6.4 with the v9 LdapAuth plugin. However, after the update, when trying to log-in, I get:

```
Sep 06 03:09:21 [01:09:21] [WRN] [22] Jellyfin.Server.Implementations.Users.UserManager: User XXXXX was found with invalid/missing Authentication Provider Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin. Assigning user to InvalidAuthProvider until this is corrected
Sep 06 03:09:21 [01:09:21] [ERR] [22] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider InvalidOrMissingAuthenticationProvider
Sep 06 03:09:21 MediaBrowser.Controller.Authentication.AuthenticationException: User Account cannot login with this provider. The Normal provider for this user cannot be found
Sep 06 03:09:21 at Jellyfin.Server.Implementations.Users.InvalidAuthProvider.Authenticate(String username, String password)
Sep 06 03:09:21 at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
Sep 06 03:09:21 [01:09:21] [INF] [22] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for XXXXX has been denied (IP: 82.251.102.162).
Sep 06 03:09:21 [01:09:21] [ERR] [22] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Invalid username or password entered. URL: http://localhost:8096/jellyfin/Users/authenticatebyname
Sep 06 03:09:21 172.18.0.1 [06/Sep/2020:01:09:21 +0000] "POST /jellyfin/Users/authenticatebyname HTTP/1.1" 401 45 "https://XXXXX/jellyfin/web/index.html"
```

And of course, I cannot use the v6 plugin with 10.6.x, so I am stuck for now on the old one :/

Any guide on how I can "convert" the existing Ldap users to the new plugin version ?

**Comment by arantes555** [comment]
My bad, messed up my dockerfile and still had the old plugin running somehow -_-

Sorry for the bother
