### ISSUE TITLE
Plugin not loading on Jellyfin 10.6.4

### ISSUE THREAD

**Issue by edofullin** [jellyfin/jellyfin-plugin-ldapauth#68]
I can't get the plugin to load inside a Debian Buster LXC container, it seems like dependencies are missing.  

The Jellyfin installation is almost fresh.

Am I missing something? 

Thanks in advance.

Here are the logs:

```
[2020-12-15 20:55:00.145 +00:00] [INF] Environment Variables: ["[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_USER, jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]", "[JELLYFIN_RESTART_OPT, --restartpath=/usr/lib/jellyfin/restart.sh]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]"]
[2020-12-15 20:55:00.150 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
[2020-12-15 20:55:00.151 +00:00] [INF] Operating system: "Linux"
[2020-12-15 20:55:00.151 +00:00] [INF] Architecture: X64
[2020-12-15 20:55:00.152 +00:00] [INF] 64-Bit Process: True
[2020-12-15 20:55:00.152 +00:00] [INF] User Interactive: True
[2020-12-15 20:55:00.152 +00:00] [INF] Processor count: 6
[2020-12-15 20:55:00.152 +00:00] [INF] Program data path: "/var/lib/jellyfin"
[2020-12-15 20:55:00.152 +00:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2020-12-15 20:55:00.153 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2020-12-15 20:55:00.395 +00:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2020-12-15 20:55:00.406 +00:00] [INF] Loading assemblies
[2020-12-15 20:55:00.423 +00:00] [INF] Loaded assembly "Jellyfin.Plugin.Anime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Anime/Jellyfin.Plugin.Anime.dll"
[2020-12-15 20:55:00.428 +00:00] [INF] Loaded assembly "LDAP-Auth, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/LDAP Authentication/LDAP-Auth.dll"
[2020-12-15 20:55:00.429 +00:00] [ERR] Error getting exported types from "LDAP-Auth, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null"
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()


[2020-12-15 20:55:00.437 +00:00] [INF] Loaded assembly "Novell.Directory.Ldap.NETStandard, Version=3.4.0.0, Culture=neutral, PublicKeyToken=510c34e9dec7f86f" from "/var/lib/jellyfin/plugins/LDAP Authentication/Novell.Directory.Ldap.NETStandard.dll"
[2020-12-15 20:55:00.438 +00:00] [ERR] Error getting exported types from "Novell.Directory.Ldap.NETStandard, Version=3.4.0.0, Culture=neutral, PublicKeyToken=510c34e9dec7f86f"
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()


[2020-12-15 20:55:02.752 +00:00] [INF] Kestrel listening on all interfaces
[2020-12-15 20:55:02.887 +00:00] [INF] Running startup tasks
[2020-12-15 20:55:02.901 +00:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 12/16/2020 02:00, which is 5:04:57.0988991 from now.
[2020-12-15 20:55:03.023 +00:00] [INF] Found ffmpeg version "4.3.1"
[2020-12-15 20:55:03.081 +00:00] [INF] Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "mp3"]
[2020-12-15 20:55:03.126 +00:00] [INF] Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-12-15 20:55:03.160 +00:00] [INF] Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
[2020-12-15 20:55:03.160 +00:00] [INF] FFmpeg: SetByArgument: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2020-12-15 20:55:03.163 +00:00] [INF] ServerId: "adbb8b3f59944c6db7e00b3de16b9fed"
[2020-12-15 20:55:03.753 +00:00] [INF] Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.10.15"
[2020-12-15 20:55:03.807 +00:00] [INF] Executed all pre-startup entry points in 0:00:00.6168013
[2020-12-15 20:55:03.808 +00:00] [INF] Core startup complete
[2020-12-15 20:55:04.155 +00:00] [INF] Watching directory /mnt/media/tv_series
[2020-12-15 20:55:04.162 +00:00] [INF] Watching directory /mnt/media/movies
[2020-12-15 20:55:04.167 +00:00] [INF] Executed all post-startup entry points in 0:00:00.3595039
[2020-12-15 20:55:04.168 +00:00] [INF] Startup complete 0:00:04.4062709
[2020-12-15 20:55:05.955 +00:00] [INF] "StartupTrigger" fired for task: "Update Plugins"
[2020-12-15 20:55:05.956 +00:00] [INF] Queueing task "PluginUpdateTask"
[2020-12-15 20:55:05.960 +00:00] [INF] Executing "Update Plugins"
[2020-12-15 20:55:06.609 +00:00] [WRN] HTTP Response 200 to "10.0.0.235". Time (slow): 0:00:01.1895637. "http://192.168.10.15:8096/System/Logs/Log?name=jellyfin20201215.log"
[2020-12-15 20:55:07.063 +00:00] [INF] "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2020-12-15 20:55:07.241 +00:00] [INF] ExecuteQueuedTasks
[2020-12-15 20:57:31.109 +00:00] [INF] WS "::ffff:10.0.0.235" request
```

**Comment by crobibero** [comment]
v10 of the ldap plugin is for Jellyfin 10.7, please downgrade to v9.

**Comment by edofullin** [comment]
I installed through the repository and I (wrongly) assumed I would get the latest package. 
Seems like I was wrong

Thanks a lot :)
