### ISSUE TITLE
Upgrade to Jellyfin v10.7.0 break LDAP plugin

### ISSUE THREAD

**Issue by gnouts** [jellyfin/jellyfin-plugin-ldapauth#76]
Using docker-compose, I just change jellyfin version, restart.
LDAP login is not working anymore. Plugin is disabled by Jellyfin at boot.
Here is my logs :

```
jellyfin_1     | [08:15:51] [INF] Loading assemblies
jellyfin_1     | [08:15:51] [INF] Loaded assembly LDAP-Auth, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/LDAP Authentication/LDAP-Auth.dll
jellyfin_1     | [08:15:51] [INF] Loaded assembly Novell.Directory.Ldap.NETStandard, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/LDAP Authentication/Novell.Directory.Ldap.NETStandard.dll
jellyfin_1     | [08:15:51] [INF] Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/Jellyfin.Plugin.OpenSubtitles.dll
jellyfin_1     | [08:15:51] [INF] Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Open Subtitles/OpenSubtitlesHandler.dll
jellyfin_1     | [08:15:51] [ERR] Failed to load assembly /config/plugins/Playback Reporting/Jellyfin.Plugin.PlaybackReporting.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
jellyfin_1     | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IReturn`1' from assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin_1     |    at System.Reflection.RuntimeAssembly.GetExportedTypes()
jellyfin_1     |    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
jellyfin_1     | [08:15:51] [ERR] Failed to load assembly /config/plugins/Reports/Jellyfin.Plugin.Reports.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
jellyfin_1     | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IReturn`1' from assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin_1     |    at System.Reflection.RuntimeAssembly.GetExportedTypes()
jellyfin_1     |    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
jellyfin_1     | [08:15:51] [ERR] Failed to load assembly /config/plugins/Trakt/Trakt.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
jellyfin_1     | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Services.IService' from assembly 'MediaBrowser.Model, Version=10.7.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin_1     |    at System.Reflection.RuntimeAssembly.GetExportedTypes()
jellyfin_1     |    at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
jellyfin_1     | [08:15:52] [ERR] DI Loop detected in the attempted creation of Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin
jellyfin_1     | [08:15:52] [ERR] Called from: Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin
jellyfin_1     | [08:15:52] [ERR] Error creating Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin
jellyfin_1     | System.Runtime.InteropServices.ExternalException (0x80004005): DI Loop detected.
jellyfin_1     |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
jellyfin_1     |    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
jellyfin_1     |    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
jellyfin_1     |    at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
jellyfin_1     |    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
jellyfin_1     |    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
jellyfin_1     |    at Emby.Server.Implementations.ApplicationHost.GetExports[T](Boolean manageLifetime)
jellyfin_1     |    at Jellyfin.Server.Implementations.Users.UserManager..ctor(JellyfinDbProvider dbProvider, IEventManager eventManager, ICryptoProvider cryptoProvider, INetworkManager networkManager, IApplicationHost appHost, IImageProcessor imageProcessor, ILogger`1 logger)
jellyfin_1     |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
jellyfin_1     |    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
jellyfin_1     |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
jellyfin_1     |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
jellyfin_1     | [08:15:54] [INF] Loaded plugin: Open Subtitles 9.0.0.0

```

**Comment by gnouts** [comment]
Nevermind, I didn't see your v10 release. Sorry for the noise.
