### ISSUE TITLE
can not work with the windows ad

### ISSUE THREAD

**Issue by wanleimin** [jellyfin/jellyfin-plugin-ldapauth#88]
Jellyfin ver: 10.7.7
server: windows 10 x64

config file
```
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <LdapServer>10.30.0.6</LdapServer>
  <LdapBaseDn>OU=vser,DC=wt,DC=local</LdapBaseDn>
  <LdapPort>389</LdapPort>
  <LdapSearchAttributes>uid, cn, mail, displayName</LdapSearchAttributes>
  <LdapUsernameAttribute>cn</LdapUsernameAttribute>
  <LdapSearchFilter>(memberOf=CN=jellyfin_users,OU=vser,DC=wt,DC=local)</LdapSearchFilter>
  <LdapAdminFilter>(memberOf=CN=vserver,OU=vser,DC=wt,DC=local)</LdapAdminFilter>
  <LdapBindUser>CN=vserver,OU=vser,DC=wt,DC=local</LdapBindUser>
  <LdapBindPassword>passwd</LdapBindPassword>
  <CreateUsersFromLdap>true</CreateUsersFromLdap>
  <UseSsl>false</UseSsl>
  <UseStartTls>false</UseStartTls>
  <SkipSslVerify>false</SkipSslVerify>
  <EnableCaseInsensitiveUsername>false</EnableCaseInsensitiveUsername>
</PluginConfiguration>
```

err log
[2021-09-12 20:21:48.499 +08:00] [ERR] [15] Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin: Found no users matching "chenmo" in LDAP search
[2021-09-12 20:21:48.502 +08:00] [ERR] [15] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "LDAP-Authentication"
MediaBrowser.Controller.Authentication.AuthenticationException: Found no LDAP users matching provided username.
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.LocateLdapUser(String username)
   at Jellyfin.Plugin.LDAP_Auth.LdapAuthenticationProviderPlugin.Authenticate(String username, String password)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2021-09-12 20:21:48.505 +08:00] [ERR] [15] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2021-09-12 20:21:48.506 +08:00] [INF] [15] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "chenmo" has been denied (IP: "192.168.16.186").
[2021-09-12 20:21:48.509 +08:00] [ERR] [15] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Invalid username or password entered". URL "POST" "/Users/authenticatebyname".
[2021-09-12 20:21:58.953 +08:00] [INF] [19] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-09-12 20:21:58.959 +08:00] [INF] [19] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2021-09-12 20:22:10.969 +08:00] [INF] [19] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.

**Comment by wanleimin** [comment]
I have solved the problem,
But I found that users can access all media libraries. 
Can you divide permissions for users or user groups?

**Comment by crobibero** [comment]
> Can you divide permissions for users or user groups?

no, that is not something the plugin provides.
